export const mallCategories = [
  { name: 'Electronics', icon: '📱' },
  { name: 'Home', icon: '🛋️' },
  { name: 'Hypermarkets', icon: '🛒' },
  { name: 'Fashion', icon: '👕' },
  { name: 'Footwear', icon: '👟' },
  { name: 'Jewelry', icon: '💎' },
  { name: 'Sportswear', icon: '🏃' },
  { name: 'Beauty', icon: '💄' },
  { name: 'Salons', icon: '✂️' },
  { name: 'Food Court', icon: '🍔' },
  { name: 'Automotive', icon: '🚗' },
  { name: 'Cinemas', icon: '🎬' },
  { name: 'Family Entertainment', icon: '🎳' },
  { name: 'Books', icon: '📚' },
  { name: 'Gifts', icon: '🎁' },
  { name: 'Financial Services', icon: '🏦' },
  { name: 'Health', icon: '💊' },
  { name: 'Outdoor', icon: '🏕️' },
] as const
